name: Build Docker images

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build crfm-helm-deps
        uses: docker/build-push-action@v6
        working-directory: docker/crfm-helm-deps
        with:
          load: true
          push: true
          tags: yifanmai/crfm-helm-deps:latest
      
      - name: Build crfm-helm
        uses: docker/build-push-action@v6
        working-directory: docker/crfm-helm
        with:
          load: true
          push: true
          tags: yifanmai/crfm-helm:latest

      - name: Build helm-run
        uses: docker/build-push-action@v6
        working-directory: docker/helm-run
        with:
          load: true
          push: true
          tags: yifanmai/helm-run:latest
