name: Publish Docker image to Google Artifact Registry

on:
  workflow_dispatch:

jobs:
  build-crfm-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set tags
        id: set-tags
        run: |
          echo "DATE_TAG=`date -u +"%Y%m%d"`" >> "$GITHUB_OUTPUT"
          echo "HASH_TAG=`git rev-parse --short HEAD`" >> "$GITHUB_OUTPUT"

      # Documentation: https://github.com/google-github-actions/auth/blob/v2.1.12/README.md
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_ARTIFACT_REPOSITORY_SA_KEY }}
          service_account: github-artifact-repository@hai-gcp-models.iam.gserviceaccount.com

      # Documentation: https://github.com/docker/login-action/blob/v3.5.0/README.md#google-artifact-registry-gar
      - name: Login to Google Artifact Registry in us-central1
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Login to Google Artifact Registry in us-central2
        uses: docker/login-action@v3
        with:
          registry: us-central2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: docker/demo-uvicorn/Dockerfile
          tags: |
            us-central1-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:latest
            us-central1-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:${{ steps.set-tags.outputs.DATE_TAG }}
            us-central1-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:${{ steps.set-tags.outputs.HASH_TAG }}
            us-central2-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:latest
            us-central2-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:${{ steps.set-tags.outputs.DATE_TAG }}
            us-central2-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:${{ steps.set-tags.outputs.HASH_TAG }}

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
