name: Build Docker images

on:
  workflow_dispatch:

jobs:
  build-crfm-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build crfm-helm
        uses: docker/build-push-action@v6
        with:
          pull: true
          load: true
          file: docker/crfm-helm/Dockerfile
          tags: yifanmai/crfm-helm:latest

      - name: Build helm-run
        uses: docker/build-push-action@v6
        with:
          push: true
          file: docker/helm-run/Dockerfile
          tags: yifanmai/helm-run:latest

      # Documentation: https://github.com/docker/login-action/blob/v3.5.0/README.md#google-artifact-registry-gar
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: <workload_identity_provider>
          service_account: <service_account>
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: <location>-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}" ./
          docker push "${{ env.AR_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
