name: Publish Docker image to Google Artifact Registry

on:
  workflow_dispatch:

jobs:
  build-crfm-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: 'actions/checkout@v4'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Documentation: https://github.com/docker/login-action/blob/v3.5.0/README.md#google-artifact-registry-gar
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_ARTIFACT_REPOSITORY_SA_KEY }}
          service_account: github-artifact-repository@hai-gcp-models.iam.gserviceaccount.com

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          file: docker/demo-uvicorn/Dockerfile
          tags: |
            us-central1-docker.pkg.dev/hai-gcp-models/helm-docker/demo-uvicorn:latest

      # - name: Build helm-run
      #   uses: docker/build-push-action@v6
      #   with:
